# -*- coding: utf-8 -*-
"""Untitled63.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r_zHU-TRrPslXpEs0G1SW3nNtsve-kd8
"""

pip install phonenumbers

import phonenumbers

from phonenumbers import geocoder, carrier, timezone

phone_number = phonenumbers.parse("+917207236442")
print(geocoder.description_for_number(phone_number, 'en'))
print(carrier.name_for_number(phone_number, 'en'))
print(timezone.time_zones_for_number(phone_number))